server:
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/veiculos
    username: postgres
    password: 1234
  jpa:
    defer-datasource-initialization: true # to allow DB initialization scripts
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    sql:
      init:
        mode: always

secret:
  key: ${JWT_SECRET:1234567890qwertyuiop}